services:
  - name: phantom-guard-bot
    type: web
    plan: free
    env: node
    buildCommand: npm install
    startCommand: node -r dotenv/config index.js dotenv_config_path=.env.production
    healthCheckPath: /
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: BOT_OWNER_ID
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: PORT
        value: 6870
      - key: NODE_ENV
        value: production
    autoDeploy: true